# Generated by Django 2.2.13 on 2021-01-14 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75, verbose_name='nombre del producto')),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.FloatField(verbose_name='Costo del producto')),
                ('existence', models.IntegerField(default=0, verbose_name='cantidad de existencia')),
                ('img', models.ImageField(blank=True, null=True, upload_to='Productos', verbose_name='imagen del producto')),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Proveedor', to='api.Seller')),
            ],
        ),
        migrations.CreateModel(
            name='Sale_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='cantidad de procutos')),
                ('total', models.FloatField(verbose_name='total del producto vendido')),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_venta_producto', to='api.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Fecha que se registra la venta')),
                ('total', models.FloatField(verbose_name='Total de la venta realizada')),
                ('activo', models.BooleanField(default=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comprador', to='api.Seller')),
                ('sale_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comprador', to='api.Sale_detail')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendedor', to='api.Seller')),
            ],
        ),
    ]
