# Generated by Django 2.2.13 on 2021-01-13 02:34

from django.db import migrations

def vendedorInicial(apps, schema_editor ):
    """    
        Crearemos datos iniciales para empezar a usar el sistema
    """
    try:
        
        #Obtenemos primero el modelo que queremos inicializar con datos        
        User = apps.get_model('auth', 'User')
        Seller = apps.get_model('api', 'Seller')

        #Ingresamos los datos con que que queremos inicializar
        usuario = User.objects.create(
            username="vendedor1",            
            #contraseña 123456, solo que esa encriptada
            password="pbkdf2_sha256$150000$GuC3z3UsxZiA$iRlgdMDESZrejTrL1B39zJ27Jid3fiPsALaI6A4urhg=",
            is_staff=True,
            is_active=True,
            is_superuser=True,
        )
        usuario2 = User.objects.create(
            username="vendedor2",            
            #contraseña 123456, solo que esa encriptada
            password="pbkdf2_sha256$150000$GuC3z3UsxZiA$iRlgdMDESZrejTrL1B39zJ27Jid3fiPsALaI6A4urhg=",
            is_staff=True,
            is_active=True,
            is_superuser=True,
        )
        Seller.objects.create(
            user = usuario,        
            phone = '54632211',
            address = 'Quetzaltengo',
            gender = 1
        )
        Seller.objects.create(
            user = usuario2,        
            phone = '38655631',
            address = 'Quetzaltengo',
            gender = 1
        )
    except  Exception as e:
        print('Except User', str(e))

def productosIniciales(apps, schema_editor):
    """
        Crearemos datos iniciales para empezar a usar el sistema
    """
    try:
        Producto = apps.get_model('api', 'Product')
        Seller = apps.get_model('api', 'Seller')
        User = apps.get_model('auth', 'User')
        
        usuario1 = User.objects.get(username='vendedor1')

        vendedor1 = Seller.objects.get(user=usuario1)
        Producto.objects.create(
            name = "Note 8",
            description = "Marca Xiaomi",
            price = 1450.00,
            existence = 15,
            provider= vendedor1
        )
        Producto.objects.create(
            name = "Note 10 Plus",
            description = "Marca Xiaomi",
            price = 1900.00,
            existence = 10,
            provider= vendedor1
        )
        Producto.objects.create(
            name = "iPhone 12",
            description = "Marca apple",
            price = 11450.00,
            existence = 5,
            provider= vendedor1
        )
        Producto.objects.create(
            name = "Samsung S20",
            description = "Marca samsung",
            price = 6450.00,
            existence = 15,
            provider= vendedor1
        )
        usuario2 = User.objects.get(username='vendedor2')
        vendedor2 = Seller.objects.get(user=usuario2)        
        Producto.objects.create(
            name = "Samsung A30",
            description = "Marca samsung",
            price = 1700.00,
            existence = 8,
            provider= vendedor1
        )
        Producto.objects.create(
            name = "Samsung A11",
            description = "Marca samsung",
            price = 1250.00,
            existence = 18,
            provider= vendedor2
        )
        Producto.objects.create(
            name = "Samsung A10",
            description = "Marca samsung",
            price = 999.00,
            existence = 18,
            provider= vendedor2
        )
        Producto.objects.create(
            name = "LG l5",
            description = "Marca LG",
            price = 650.00,
            existence = 20,
            provider= vendedor2
        )
        Producto.objects.create(
            name = "Motorola Edge+",
            description = "Marca Motorola",
            price = 1800.00,
            existence = 28,
            provider= vendedor2
        )
        Producto.objects.create(
            name = "Moto G 5 Plus",
            description = "Marca Motorola",
            price = 5000.00,
            existence = 9,
            provider= vendedor2
        )
        Producto.objects.create(
            name = "Samsung Galaxy M11",
            description = "Marca samsung",
            price = 3999.00,
            existence = 12,
            provider= vendedor1
        )
        Producto.objects.create(
            name = "Samsung Galaxy Z Flip",
            description = "Marca samsung",
            price = 10500.00,
            existence = 8,
            provider= vendedor1
        )
    except Exception as e:
        print('Except User', str(e))
    

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_product_sale_sale_detail'),
    ]

    operations = [
        migrations.RunPython(vendedorInicial),
        migrations.RunPython(productosIniciales)
    ]

